project_name: github_actions_etl_template
description: Template for ETL processes using GitHub Actions
author: Andres Chirinos
created_date: 2025-04-28
version: 1.0.0

github_actions:
  artifact:
    logs:
      retention_days: 14
    data:
      retention_days: 14

drive:
  folder_id: "1J-Il-mSrw08ie3BWVQMZYbLforl1UH-B"

kaggle:
  dataset_id: "andreschirinos/github-actions-etl-template"
  is_public: true
