project_name: web-scraping
description: A web scraping project that extracts data from a website and processes it for analysis.
author: Andres Chirinos
created_date: 2025-06-24
version: 1.0.0

github_actions:
  artifact:
    logs:
      retention_days: 14
    data:
      retention_days: 14

drive:
  folder_id: ""

kaggle:
  dataset_id: ""
  is_public: true
