name: umsa-crawl-1
collection: umsa-crawl-1
workers: 8 
saveState: always

blockRules:
  - url: google-analytics.com
  - url: googletagmanager.com
  - url: googlesyndication.com
  - url: yandex.ru
  - url: liveinternet.ru
  - url: hotlog.ru
  - url: openstat.net
  - url: mycounter.ua
  - url: facebook.(com|net)
  - url: www.acint.net
  - url: news.2xclick.ru
  - url: culturaltracking.ru
  - url: sape.ru

seeds:
  - url: https://umsa.bo/
    depth: 1
    scoreType: "host"
    # include:
    # exclude:

generateWACZ: true

warcinfo:
  operator: my-org
  hostname: hostname.my-org

screenshot: fullPage